from pydantic import BaseModel, Field
from typing import List, Optional, Literal
from enum import Enum

class HallucinationFingerprint(BaseModel):
    type: Literal["fabrication", "outdated_fact", "false_authority", "speculation", "none"] = Field(..., description="The specific type of hallucination or error detected.")
    description: str = Field(..., description="A technical explanation of why this is categorized as such.")
    impact_level: Literal["critical", "high", "medium", "low", "none"] = Field(..., description="The potential severity of this error.")

class ClaimType(str, Enum):
    FACTUAL_VERIFIABLE = "factual_verifiable"
    FACTUAL_UNVERIFIABLE = "factual_unverifiable"
    INFERENTIAL = "inferential"
    SPECULATIVE = "speculative"
    AUTHORITY_REFERENCE = "authority_reference"

class ScoreBreakdown(BaseModel):
    evidence_coverage: float = Field(..., description="Percentage of claims with verifiable backing (0-100)")
    claim_verifiability: float = Field(..., description="Ratio of claims that are factual/verifiable vs vague (0-100)")
    confidence_evidence_gap: float = Field(..., description="Gap between assertiveness and evidence strength (0-100)")

class ExecutiveBrief(BaseModel):
    headline_risk_assessment: str = Field(..., description="A one-line verdict for a CEO (e.g., 'Do Not Ship').")
    business_impact: str = Field(..., description="Plain-language explanation of legal/brand risk.")
    compliance_flags: List[str] = Field(default=[], description="List of specific compliance issues (e.g., 'GDPR', 'False Advertising').")
    action_recommendation: Literal["SHIP", "HOLD", "REJECT"] = Field(..., description="The final automated decision.")

class Claim(BaseModel):
    original_text: str = Field(..., description="The original sentence from the LLM response")
    quote: str = Field(..., description="The exact substring/quote from the text corresponding to this claim")
    atomic_fact: str = Field(..., description="The simplified atomic fact to be verified")
    claim_type: ClaimType = Field(default=ClaimType.FACTUAL_VERIFIABLE, description="The nature of the claim")
    status: Literal["verified", "contradicted", "unverified", "processing", "error"] = "processing"
    confidence_score: float = 0.0
    evidence_strength: float = Field(default=0.0, description="Strength of the evidence (0.0-1.0)")
    assertiveness_score: float = 0.0
    evidence: List[str] = []
    explanation: str = ""
    fingerprint: Optional[HallucinationFingerprint] = None

class AnalysisRequest(BaseModel):
    text: str = Field(..., description="The text generated by an LLM to be analyzed")
    question: Optional[str] = Field(default=None, description="Optional user question to focus the audit")

class AnalysisResponse(BaseModel):
    integrity_score: float = Field(default=0.0, description="Overall honesty/accuracy score")
    hallucination_score: float = Field(default=0.0, description="Canonical hallucination risk score")
    confidence_gap: float = Field(default=0.0, description="Gap between confidence and evidence")
    simple_explainer: str = Field(default="", description="Simple string explaining the risk")
    risk_score: float # Kept for backward compatibility if needed, same as hallucination_score
    confidence_interval: List[float] = Field(default=[0.0, 0.0], description="[min_score, max_score] confidence band")
    question: Optional[str] = None
    score_breakdown: Optional[ScoreBreakdown] = None
    claims: List[Claim]
    summary_report: str
    executive_brief: Optional[ExecutiveBrief] = None
